let csrf = '', me = null, activeTab = 'overview', selectedCandidate = '', selectedSubject = '', selectedCredentialSubject = '', selectedTrackSubject = '';
let gpsTrackMap = null, gpsTrackLayers = null, gpsTrackTile = null, gpsTrackHours = 12;
const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function api(url,opts={}){opts.headers={...(opts.headers||{})};if(opts.body&&!opts.headers['Content-Type'])opts.headers['Content-Type']='application/json';if(opts.method&&opts.method!=='GET'&&csrf)opts.headers['X-CSRF-Token']=csrf;const r=await fetch(url,opts);let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.detail||`HTTP ${r.status}`);return data}
function badge(v){const map={running:['运行中','ok'],scheduled:['已预约','info'],completed:['完成',''],closed:['完成',''],canceled:['取消',''],available:['可用','ok'],repair:['维修','warn'],disabled:['停用','danger'],open:['待处理','danger'],handling:['处理中','warn'],resolved:['已解决','ok'],connected:['已接入','ok'],reserved:['预留','info'],manual:['人工链路','warn'],offline:['离线导入',''],pi:['PI','info'],ra:['RA',''],active:['启用','ok'],inactive:['禁用','danger'],ok:['完整','ok'],missing:['缺失','danger'],pending:['待完成','warn'],valid:['有效','ok'],insufficient:['样本不足','warn'],unreadable:['无法解析','danger']};const x=map[v]||[v||'—',''];return `<span class="badge ${x[1]}">${esc(x[0])}</span>`}
function fmtTime(s){if(!s)return '—';try{return new Date(s).toLocaleString('zh-CN',{hour12:false})}catch{return s}}
function gpsBadge(v){const map={live:['在线','ok'],stale:['延迟','warn'],offline:['离线','danger'],never:['无数据',''],unknown:['未知','warn']};const x=map[v]||map.unknown;return `<span class="badge ${x[1]}">${x[0]}</span>`}

function showAuth(which){$('setupView').classList.toggle('hidden',which!=='setup');$('loginView').classList.toggle('hidden',which!=='login');$('appView').classList.add('hidden')}
function showTab(name){if(name==='system'&&me?.role!=='pi')return;activeTab=name;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tabpage').forEach(x=>x.classList.add('hidden'));$('tab-'+name).classList.remove('hidden');loadTab(name)}
async function initialize(){try{const x=await api('/api/v1/web/me');csrf=x.csrf_token;me=x;return enterApp()}catch{}try{const s=await api('/api/v1/web/setup-status');if(!s.initialized){$('setupTokenWrap').classList.toggle('hidden',!s.setup_token_required);showAuth('setup')}else showAuth('login')}catch(e){showAuth('login');$('loginError').textContent=e.message}}
async function firstSetup(){const p=$('setupPassword').value,p2=$('setupPassword2').value;$('setupError').textContent='';if(p!==p2){$('setupError').textContent='两次密码不一致';return}try{const data=await api('/api/v1/web/setup',{method:'POST',body:JSON.stringify({display_name:$('setupDisplay').value,username:$('setupUser').value,password:p,setup_token:$('setupToken').value})});csrf=data.csrf_token;me=data.user;enterApp()}catch(e){$('setupError').textContent=e.message}}
async function login(){try{const data=await api('/api/v1/web/login',{method:'POST',body:JSON.stringify({username:$('loginUser').value,password:$('loginPassword').value})});csrf=data.csrf_token;me=data.user;enterApp()}catch(e){$('loginError').textContent=e.message}}
async function enterApp(){if(!me){try{const x=await api('/api/v1/web/me');csrf=x.csrf_token;me=x}catch{return initialize()}}$('setupView').classList.add('hidden');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('who').textContent=`${me.display_name||me.username} · ${me.role.toUpperCase()}`;$('systemTab').classList.toggle('hidden',me.role!=='pi');if(activeTab==='system'&&me.role!=='pi')activeTab='overview';await loadTab(activeTab)}
async function logout(){try{await api('/api/v1/web/logout',{method:'POST',body:'{}'})}catch{}location.reload()}
async function loadTab(name){try{if(name==='overview')await renderDashboard();if(name==='subjects')await renderSubjects();if(name==='candidates')await renderCandidates();if(name==='qc')await renderDailyQc();if(name==='devices')await renderDevices();if(name==='incidents')await renderIncidents();if(name==='sources')await renderSources();if(name==='architecture')await renderArchitecture();if(name==='system')await renderUsers()}catch(e){toast(e.message)}}

async function renderDashboard(){
  const d=await api('/api/v1/web/dashboard');
  const labels=[['候选池','candidates'],['已预约','scheduled'],['运行中','running'],['开放异常','open_incidents'],['可用设备包','available_packs'],['已有GPS被试','gps_subjects'],['今日问卷提交','questionnaire_today']];
  $('metrics').innerHTML=labels.map(([l,k])=>`<div class="metric"><div class="label">${l}</div><div class="value">${d.metrics[k]??0}</div></div>`).join('');
  $('runningList').innerHTML=d.running.length?d.running.map(x=>`<div class="issue"><div class="issue-title"><strong>${esc(x.participant_id)}</strong>${badge(x.status)}</div><p>${esc(x.pack_id||'未绑定设备')} · GPS ${x.gps_last_received_at_utc?`最近 ${fmtTime(x.gps_last_received_at_utc)}`:'暂无回传'} · 今日问卷 ${x.questionnaire_today_completed||0}/2</p></div>`).join(''):'<div class="muted">暂无运行中被试</div>';
  $('attentionList').innerHTML=d.incidents.length?d.incidents.map(x=>`<div class="issue"><div class="issue-title"><strong>${esc(x.participant_id||'—')} · ${esc(x.summary||x.incident_type)}</strong>${badge(x.status)}</div><p>${esc(x.source)} · ${esc(x.date_local)}</p></div>`).join(''):'<div class="muted">暂无开放异常</div>';
}

async function renderCandidates(){const a=await api('/api/v1/web/candidates');$('candidateRows').innerHTML=a.map(x=>`<tr><td>${esc(x.name||'—')}</td><td>${esc(x.phone)}<br><span class="muted">${esc(x.wechat)}</span></td><td>${esc(x.source)}${x.source_seq?`<br><span class="muted">序号 ${esc(x.source_seq)}</span>`:''}${!x.in_latest_snapshot?'<br><span class="muted">不在最新累计表</span>':''}</td><td>${esc([x.sex,x.age_group,x.identity_type,x.light_type].filter(Boolean).join(' · '))}</td><td>${esc([x.work_district,x.home_district].filter(Boolean).join(' / '))}</td><td>${esc(x.phone_os)}</td><td>${esc(x.linked_participant_id||'—')}</td><td>${!x.in_latest_snapshot&&x.linked_participant_id?'历史已入组':x.linked_participant_id?'已入组':`<button class="btn small" data-promote="${esc(x.candidate_uid)}">赋ID/预约</button>`}</td></tr>`).join('');document.querySelectorAll('[data-promote]').forEach(b=>b.addEventListener('click',()=>openPromote(b.dataset.promote)))}
function bytesToBase64(buffer){const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function importS0(){const file=$('s0File').files[0];if(!file){toast('请选择问卷星 CSV/XLSX');return}$('importS0Btn').disabled=true;try{const result=await api('/api/v1/web/candidates/import-s0',{method:'POST',body:JSON.stringify({filename:file.name,content_b64:bytesToBase64(await file.arrayBuffer())})});$('s0Result').textContent=`原始 ${result.total} 行 · 入池 ${result.imported} · 过滤 ${result.filtered}${result.duplicate?' · 已导入过':''}`;toast(result.duplicate?'该文件已导入过，未重复写入':'S0 候选池导入完成');await renderCandidates()}finally{$('importS0Btn').disabled=false}}
async function addCandidate(){const body={name:$('cName').value,phone:$('cPhone').value,wechat:$('cWechat').value,source:$('cSource').value,sex:$('cSex').value,age_group:$('cAge').value,identity_type:$('cIdentity').value,phone_os:$('cOs').value,work_district:$('cWork').value,home_district:$('cHome').value,availability:$('cAvail').value,notes:$('cNotes').value};await api('/api/v1/web/candidates',{method:'POST',body:JSON.stringify(body)});toast('已加入候选池');await renderCandidates()}
function openPromote(uid){selectedCandidate=uid;const t=new Date().toISOString().slice(0,10);$('pStart').value=t;const e=new Date();e.setDate(e.getDate()+13);$('pEnd').value=e.toISOString().slice(0,10);$('promoteDialog').showModal()}
async function promote(){const body={participant_id:$('pId').value,batch_id:$('pBatch').value,expected_start:$('pStart').value,expected_end:$('pEnd').value,pack_id:$('pPack').value,assigned_ra:$('pRa').value};await api(`/api/v1/web/candidates/${selectedCandidate}/promote`,{method:'POST',body:JSON.stringify(body)});$('promoteDialog').close();toast('已创建预约');await renderCandidates()}

async function renderSubjects(){
  const a=await api('/api/v1/web/subjects');
  $('subjectRows').innerHTML=a.map(x=>`<tr><td><strong>${esc(x.participant_id)}</strong></td><td>${esc(x.name||'—')}<br><span class="muted">${esc(x.phone||'')}</span></td><td>${badge(x.status)}</td><td>${esc(x.start_date||x.expected_start||'—')} → ${esc(x.end_date||x.expected_end||'—')}</td><td>${esc(x.pack_id||'—')}</td><td>${esc(x.assigned_ra||'—')}</td><td>${gpsBadge(x.gps_status)} <span class="muted">${x.gps_last_received_at_utc?fmtTime(x.gps_last_received_at_utc):'暂无回传'}</span><br><button class="btn small" data-gps-track="${esc(x.participant_id)}">轨迹</button></td><td>${x.questionnaire_today_completed||0}/2</td><td>${x.lighting_today?.uploaded?`${badge(x.lighting_today.quality)} ${x.lighting_today.valid_pct??''}%`:'未上传'}</td><td>${x.portal_enabled?badge('connected'):'未生成'}</td><td><div class="row">${x.status==='scheduled'?`<button class="btn small" data-start="${x.participant_id}" data-pack="${esc(x.pack_id)}">启动</button>`:''}<button class="btn small" data-credentials="${x.participant_id}">查看凭据</button></div></td></tr>`).join('');
  document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>openStart(b.dataset.start,b.dataset.pack)));
  document.querySelectorAll('[data-credentials]').forEach(b=>b.addEventListener('click',()=>openCredentials(b.dataset.credentials)));
  document.querySelectorAll('[data-gps-track]').forEach(b=>b.addEventListener('click',()=>openGpsTrack(b.dataset.gpsTrack)));
}
function formatGap(seconds){if(seconds===null||seconds===undefined)return '—';return seconds>=60?`${(seconds/60).toFixed(1)} min`:`${Number(seconds).toFixed(0)} s`}
function ensureGpsMap(config){
  if(!gpsTrackMap){gpsTrackMap=L.map('gpsTrackMap',{preferCanvas:true});gpsTrackLayers=L.layerGroup().addTo(gpsTrackMap)}
  if(!gpsTrackTile)gpsTrackTile=L.tileLayer(config.tile_url,{attribution:config.attribution,maxZoom:19}).addTo(gpsTrackMap);
}
async function openGpsTrack(pid){selectedTrackSubject=pid;gpsTrackHours=12;$('gpsTrackTitle').textContent=`被试 ${pid} · GPS 轨迹`;if(!$('gpsTrackDialog').open)$('gpsTrackDialog').showModal();await loadGpsTrack(gpsTrackHours)}
async function loadGpsTrack(hours){
  if(!selectedTrackSubject)return;gpsTrackHours=Number(hours);document.querySelectorAll('[data-track-hours]').forEach(b=>b.classList.toggle('active',Number(b.dataset.trackHours)===gpsTrackHours));
  $('gpsTrackMessage').className='muted track-message';$('gpsTrackMessage').textContent='正在读取轨迹…';
  try{
    const data=await api(`/api/v1/web/subjects/${encodeURIComponent(selectedTrackSubject)}/gps-track?hours=${gpsTrackHours}`);
    $('trackLatest').textContent=fmtTime(data.latest_recorded_at_utc);$('trackCount').textContent=String(data.total_point_count);$('trackGap').textContent=formatGap(data.max_gap_seconds);$('trackPoor').textContent=data.poor_accuracy_percentage===null?'—':`${data.poor_accuracy_percentage.toFixed(1)}%`;
    $('gpsTrackWindow').textContent=`最近 ${data.window_hours} h · 显示 ${data.points.length} / ${data.total_point_count} 点`;
    ensureGpsMap(data.map);gpsTrackLayers.clearLayers();
    if(!data.points.length){$('gpsTrackMessage').textContent='该时间窗内没有 GPS 位置记录';gpsTrackMap.setView([39.9,116.4],10);setTimeout(()=>gpsTrackMap.invalidateSize(),0);return}
    const segments=[];let segment=[];
    for(const point of data.points){if(point.break_before&&segment.length){segments.push(segment);segment=[]}segment.push([point.lat,point.lon])}if(segment.length)segments.push(segment);
    segments.filter(x=>x.length>1).forEach(x=>L.polyline(x,{color:'#2563a6',weight:4,opacity:.85}).addTo(gpsTrackLayers));
    const first=data.points[0],latest=data.points[data.points.length-1];
    L.circleMarker([first.lat,first.lon],{radius:6,color:'#fff',weight:2,fillColor:'#23834a',fillOpacity:1}).bindTooltip('起点').addTo(gpsTrackLayers);
    L.circleMarker([latest.lat,latest.lon],{radius:7,color:'#fff',weight:2,fillColor:'#c43d3d',fillOpacity:1}).bindTooltip('最新点').addTo(gpsTrackLayers);
    const bounds=L.latLngBounds(data.points.map(x=>[x.lat,x.lon]));bounds.isValid()&&data.points.length>1?gpsTrackMap.fitBounds(bounds,{padding:[24,24],maxZoom:17}):gpsTrackMap.setView([latest.lat,latest.lon],16);
    $('gpsTrackMessage').textContent=data.max_gap_seconds>data.gap_warning_seconds?`超过 ${data.gap_warning_seconds} s 的缺失时段已断开显示`:'轨迹连续时段已按时间连接';setTimeout(()=>gpsTrackMap.invalidateSize(),0);
  }catch(e){$('gpsTrackMessage').className='track-message error';$('gpsTrackMessage').textContent=e.message}
}
async function openCredentials(pid){selectedCredentialSubject=pid;const x=await api(`/api/v1/web/subjects/${pid}/credentials`);$('credentialTitle').textContent=`被试 ${pid} 凭据`;$('credGpsUrl').value=`${location.origin}/api/v1/gps/owntracks`;$('credGpsUser').value=pid;$('credGpsPassword').value=x.gps_password||'';$('credPortal').value=x.portal_path?location.origin+x.portal_path:'';$('credGpsHint').textContent=x.gps_exists&&!x.gps_password?'旧 GPS 密码无法恢复，请重置一次。':x.gps_password?'可随时复制；重置后旧密码立即失效。':'尚未生成。';$('credPortalHint').textContent=x.portal_exists&&!x.portal_path?'旧工作入口无法恢复，请重置一次。':x.portal_path?'可随时复制；重置后旧链接立即失效。':'尚未生成。';$('credGpsRotate').textContent=x.gps_exists?'重置 GPS 密码':'生成 GPS 密码';$('credPortalRotate').textContent=x.portal_exists?'重置工作入口':'生成工作入口';if(!$('credentialDialog').open)$('credentialDialog').showModal()}
async function rotateGps(){if(!confirm(`为 ${selectedCredentialSubject} 生成新的 GPS 密码？已有密码会立即失效。`))return;await api(`/api/v1/web/subjects/${selectedCredentialSubject}/gps-credential`,{method:'POST',body:'{}'});await openCredentials(selectedCredentialSubject)}
async function rotatePortal(){if(!confirm(`为 ${selectedCredentialSubject} 生成新的工作入口？已有链接会立即失效。`))return;await api(`/api/v1/web/subjects/${selectedCredentialSubject}/portal`,{method:'POST',body:'{}'});await openCredentials(selectedCredentialSubject);await renderSubjects()}
async function copyCredential(id){const value=$(id).value;if(!value){toast('请先生成或重置该凭据');return}try{await navigator.clipboard.writeText(value);toast('已复制')}catch{window.prompt('请复制：',value)}}
function openStart(pid,pack){selectedSubject=pid;$('sPack').value=pack||'';const t=new Date().toISOString().slice(0,10);$('sStart').value=t;const e=new Date();e.setDate(e.getDate()+13);$('sEnd').value=e.toISOString().slice(0,10);$('startDialog').showModal()}
async function startSubject(){await api(`/api/v1/web/subjects/${selectedSubject}/start`,{method:'POST',body:JSON.stringify({pack_id:$('sPack').value,start_date:$('sStart').value,end_date:$('sEnd').value})});$('startDialog').close();toast('已启动运行');await renderSubjects()}

function yesNo(value){return value?badge('ok'):badge('missing')}
async function renderDailyQc(){const q=await api('/api/v1/web/daily-qc');const labels=[['暴露日','total'],['完整','ok'],['异常','missing'],['今日待完成','pending']];$('qcMetrics').innerHTML=labels.map(([label,key])=>`<div class="metric"><div class="label">${label}</div><div class="value">${q.summary[key]||0}</div></div>`).join('');$('qcRows').innerHTML=q.rows.slice().reverse().map(x=>`<tr><td>${esc(x.date_local)}</td><td><strong>${esc(x.participant_id)}</strong></td><td>${x.study_day}</td><td>${badge(x.status)}</td><td>${yesNo(x.evening)}</td><td>${badge(x.lighting)}${x.light_valid_pct!==null?` ${x.light_valid_pct}%`:''}</td><td>${yesNo(x.gps)}</td><td>${yesNo(x.morning)}</td><td>${esc(x.missing_items||'—')}</td></tr>`).join('');const light=await api('/api/v1/web/lighting');$('lightingRows').innerHTML=light.map(x=>`<tr><td>${esc(x.date_local)}</td><td><strong>${esc(x.participant_id)}</strong></td><td>${esc(x.original_filename)}</td><td>${badge(x.quality)}</td><td>${x.records_valid}/${x.records_total}</td><td>${x.valid_pct}%</td><td>${fmtTime(x.uploaded_at_utc)}</td><td>${esc(x.parse_error||'—')}</td></tr>`).join('')}
async function runDailyQc(){$('runQcBtn').disabled=true;try{const q=await api('/api/v1/web/daily-qc/run',{method:'POST',body:'{}'});toast(`核查完成：完整 ${q.summary.ok}，异常 ${q.summary.missing}，待完成 ${q.summary.pending}`);await renderDailyQc()}finally{$('runQcBtn').disabled=false}}

async function renderDevices(){const a=await api('/api/v1/web/devices');$('deviceRows').innerHTML=a.map(x=>`<tr><td><strong>${esc(x.pack_id)}</strong></td><td>${badge(x.status)}</td><td>${esc(x.current_participant_id||'—')}</td><td>${esc(x.light_serial||'—')}</td><td>${esc(x.ax3_serial||'—')}</td><td>${esc(x.issued_date||'—')}</td><td>${esc(x.expected_return_date||'—')}</td><td>${esc(x.notes||'')}</td></tr>`).join('')}
async function saveDevice(){await api('/api/v1/web/devices',{method:'POST',body:JSON.stringify({pack_id:$('dPack').value,status:$('dStatus').value,light_serial:$('dLight').value,ax3_serial:$('dAx3').value,notes:$('dNotes').value})});toast('设备包已保存');await renderDevices()}
async function renderIncidents(){const a=await api('/api/v1/web/incidents');$('incidentList').innerHTML=a.length?a.map(x=>`<div class="issue"><div class="issue-title"><div><strong>${esc(x.participant_id||'—')} · ${esc(x.summary||x.incident_type)}</strong> ${badge(x.status)}</div><span class="muted">${esc(x.date_local)}</span></div><p>${esc(x.source)} · ${esc(x.notes||'')}</p><div class="row" style="margin-top:7px">${x.status==='open'?`<button class="btn small" data-istatus="${x.incident_uid}" data-v="handling">标记处理中</button>`:''}${x.status!=='closed'?`<button class="btn small" data-istatus="${x.incident_uid}" data-v="closed">关闭</button>`:''}</div></div>`).join(''):'<div class="muted">暂无异常</div>';document.querySelectorAll('[data-istatus]').forEach(b=>b.addEventListener('click',()=>setIncidentStatus(b.dataset.istatus,b.dataset.v)))}
async function addIncident(){await api('/api/v1/web/incidents',{method:'POST',body:JSON.stringify({participant_id:$('iPid').value,date_local:$('iDate').value,source:$('iSource').value,incident_type:$('iType').value,severity:$('iSeverity').value,summary:$('iSummary').value,notes:$('iNotes').value})});toast('已加入异常中心');await renderIncidents()}
async function setIncidentStatus(uid,v){await api(`/api/v1/web/incidents/${uid}/status`,{method:'POST',body:JSON.stringify({status:v})});await renderIncidents()}

async function renderSources(){const a=await api('/api/v1/web/data-sources');$('sourceGrid').innerHTML=a.map(x=>`<div class="source"><div class="row" style="justify-content:space-between"><div class="name">${esc(x.name)}</div>${badge(x.status)}</div><dl><dt>进入方式</dt><dd>${esc(x.acquisition)}</dd><dt>存储</dt><dd>${esc(x.storage)}</dd><dt>自动化</dt><dd>${esc(x.automation)}</dd>${x.records!==null?`<dt>当前记录</dt><dd>${x.records}</dd>`:''}${x.last_event?`<dt>最近事件</dt><dd>${fmtTime(x.last_event)}</dd>`:''}</dl></div>`).join('')}
async function renderArchitecture(){const x=await api('/api/v1/web/architecture');$('architectureView').innerHTML=`<div class="arch"><div class="arch-row"><div class="node"><div class="k">Operators</div><strong>PI / RA Admin</strong><span class="muted">管理被试、设备与异常</span></div><div class="node"><div class="k">Participant</div><strong>专属工作入口</strong><span class="muted">/p/&lt;token&gt; · 无需姓名/编号</span></div><div class="node"><div class="k">Interface</div><strong>LEHUE Web</strong><span class="muted">管理端 + 被试端</span></div><div class="node"><div class="k">Backend</div><strong>FastAPI</strong><span class="muted">身份、任务、API、规则</span></div></div><div class="arrow">↓</div><div class="arch-row"><div class="node"><div class="k">Realtime</div><strong>GPS / OwnTracks</strong><span class="muted">已接入</span></div><div class="node"><div class="k">Native task</div><strong>LEHUE Questionnaire</strong><span class="muted">已接入 · 自动绑定 Study Day</span></div><div class="node"><div class="k">File upload</div><strong>Lighting</strong><span class="muted">已接入 · 旧版兼容解析/QC</span></div><div class="node"><div class="k">Offline</div><strong>AX3</strong><span class="muted">回收后导入</span></div></div><div class="arrow">↓</div><div class="arch-row"><div class="node"><div class="k">Sensitive</div><strong>Identity DB</strong><span class="muted">姓名、电话、管理员账号、S0</span></div><div class="node"><div class="k">Pseudonymous</div><strong>Operations DB</strong><span class="muted">被试ID、GPS、问卷、Lighting QC、设备、异常</span></div><div class="node"><div class="k">Raw vault</div><strong>Persistent volume / future OSS</strong><span class="muted">GPS JSONL 与 Lighting 原始文件</span></div><div class="node"><div class="k">Scientific analysis</div><strong>Local workstation</strong><span class="muted">科研QC与统计分析不搬云端</span></div></div><div class="card" style="box-shadow:none;margin:8px 0 0;background:var(--soft2)"><strong>边界：</strong> ${esc(x.principle)}</div></div>`}

async function renderUsers(){const a=await api('/api/v1/web/users');$('userRows').innerHTML=a.map(x=>`<tr><td><strong>${esc(x.username)}</strong></td><td>${esc(x.display_name||'—')}</td><td>${badge(x.role)}</td><td>${badge(x.is_active?'active':'inactive')}</td><td>${fmtTime(x.created_at_utc)}</td><td><div class="user-actions"><button class="btn small" data-reset="${esc(x.username)}">重置密码</button>${x.username!==me.username?`<button class="btn small ${x.is_active?'danger':''}" data-active="${esc(x.username)}" data-value="${x.is_active?'0':'1'}">${x.is_active?'禁用':'启用'}</button>`:''}</div></td></tr>`).join('');document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',()=>resetUser(b.dataset.reset)));document.querySelectorAll('[data-active]').forEach(b=>b.addEventListener('click',()=>setUserActive(b.dataset.active,b.dataset.value==='1')))}
async function addUser(){const body={username:$('uUsername').value,display_name:$('uDisplay').value,role:$('uRole').value,password:$('uPassword').value};const x=await api('/api/v1/web/users',{method:'POST',body:JSON.stringify(body)});alert(`账号已创建\n用户名: ${x.username}\n密码: ${x.password}\n\n请立即交给对应协作者。`);$('uPassword').value='';await renderUsers()}
async function setUserActive(username,isActive){if(!confirm(`${isActive?'启用':'禁用'}账号 ${username}？`))return;await api(`/api/v1/web/users/${encodeURIComponent(username)}/active`,{method:'POST',body:JSON.stringify({is_active:isActive})});await renderUsers()}
async function resetUser(username){const p=prompt(`重置 ${username} 的密码。可留空自动生成强密码：`,'');if(p===null)return;const x=await api(`/api/v1/web/users/${encodeURIComponent(username)}/reset-password`,{method:'POST',body:JSON.stringify({password:p})});alert(`密码已重置\n用户名: ${x.username}\n新密码: ${x.password}\n\n该账号现有登录会话已失效。`)}
function downloadBackup(){location.href='/api/v1/web/backup'}

$('setupBtn').addEventListener('click',firstSetup);$('loginBtn').addEventListener('click',login);$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',()=>loadTab(activeTab));$('addCandidateBtn').addEventListener('click',addCandidate);$('importS0Btn').addEventListener('click',importS0);$('runQcBtn').addEventListener('click',runDailyQc);$('saveDeviceBtn').addEventListener('click',saveDevice);$('addIncidentBtn').addEventListener('click',addIncident);$('promoteSubmit').addEventListener('click',promote);$('startSubmit').addEventListener('click',startSubject);$('addUserBtn').addEventListener('click',addUser);$('backupBtn').addEventListener('click',downloadBackup);$('credGpsRotate').addEventListener('click',rotateGps);$('credPortalRotate').addEventListener('click',rotatePortal);document.querySelectorAll('[data-copy-credential]').forEach(b=>b.addEventListener('click',()=>copyCredential(b.dataset.copyCredential)));
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
document.querySelectorAll('[data-track-hours]').forEach(b=>b.addEventListener('click',()=>loadGpsTrack(b.dataset.trackHours)));
$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('setupPassword2').addEventListener('keydown',e=>{if(e.key==='Enter')firstSetup()});
initialize();
