let csrf='', me=null, activeTab='overview', selectedCandidate='', selectedSubject='';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function api(url,opts={}){opts.headers={...(opts.headers||{})};if(opts.body&&!opts.headers['Content-Type'])opts.headers['Content-Type']='application/json';if(opts.method&&opts.method!=='GET'&&csrf)opts.headers['X-CSRF-Token']=csrf;const r=await fetch(url,opts);let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.detail||`HTTP ${r.status}`);return data}
function badge(v){const map={running:['运行中','ok'],scheduled:['已预约','info'],completed:['完成',''],closed:['完成',''],canceled:['取消',''],available:['可用','ok'],repair:['维修','warn'],disabled:['停用','danger'],open:['待处理','danger'],handling:['处理中','warn'],resolved:['已解决','ok'],connected:['已接入','ok'],reserved:['预留','info'],manual:['人工链路','warn'],offline:['离线导入',''],pi:['PI','info'],ra:['RA',''],active:['启用','ok'],inactive:['禁用','danger']};const x=map[v]||[v||'—',''];return `<span class="badge ${x[1]}">${esc(x[0])}</span>`}
function fmtTime(s){if(!s)return '—';try{return new Date(s).toLocaleString('zh-CN',{hour12:false})}catch{return s}}
function showAuth(which){$('setupView').classList.toggle('hidden',which!=='setup');$('loginView').classList.toggle('hidden',which!=='login');$('appView').classList.add('hidden')}
function showTab(name){if(name==='system'&&me?.role!=='pi')return;activeTab=name;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tabpage').forEach(x=>x.classList.add('hidden'));$('tab-'+name).classList.remove('hidden');loadTab(name)}
async function initialize(){try{const x=await api('/api/v1/web/me');csrf=x.csrf_token;me=x;return enterApp()}catch{}try{const s=await api('/api/v1/web/setup-status');if(!s.initialized){$('setupTokenWrap').classList.toggle('hidden',!s.setup_token_required);showAuth('setup')}else showAuth('login')}catch(e){showAuth('login');$('loginError').textContent=e.message}}
async function firstSetup(){const p=$('setupPassword').value,p2=$('setupPassword2').value;$('setupError').textContent='';if(p!==p2){$('setupError').textContent='两次密码不一致';return}try{const data=await api('/api/v1/web/setup',{method:'POST',body:JSON.stringify({display_name:$('setupDisplay').value,username:$('setupUser').value,password:p,setup_token:$('setupToken').value})});csrf=data.csrf_token;me=data.user;enterApp()}catch(e){$('setupError').textContent=e.message}}
async function login(){try{const data=await api('/api/v1/web/login',{method:'POST',body:JSON.stringify({username:$('loginUser').value,password:$('loginPassword').value})});csrf=data.csrf_token;me=data.user;enterApp()}catch(e){$('loginError').textContent=e.message}}
async function enterApp(){if(!me){try{const x=await api('/api/v1/web/me');csrf=x.csrf_token;me=x}catch{return initialize()}}$('setupView').classList.add('hidden');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('who').textContent=`${me.display_name||me.username} · ${me.role.toUpperCase()}`;$('systemTab').classList.toggle('hidden',me.role!=='pi');if(activeTab==='system'&&me.role!=='pi')activeTab='overview';await loadTab(activeTab)}
async function logout(){try{await api('/api/v1/web/logout',{method:'POST',body:'{}'})}catch{}location.reload()}
async function loadTab(name){try{if(name==='overview')await renderDashboard();if(name==='subjects')await renderSubjects();if(name==='candidates')await renderCandidates();if(name==='devices')await renderDevices();if(name==='incidents')await renderIncidents();if(name==='sources')await renderSources();if(name==='architecture')await renderArchitecture();if(name==='system')await renderUsers()}catch(e){toast(e.message)}}
async function renderDashboard(){const d=await api('/api/v1/web/dashboard');const labels=[['候选池','candidates'],['已预约','scheduled'],['运行中','running'],['开放异常','open_incidents'],['可用设备包','available_packs'],['已有GPS被试','gps_subjects']];$('metrics').innerHTML=labels.map(([l,k])=>`<div class="metric"><div class="label">${l}</div><div class="value">${d.metrics[k]}</div></div>`).join('');$('runningList').innerHTML=d.running.length?d.running.map(x=>`<div class="issue"><div class="issue-title"><strong>${esc(x.participant_id)}</strong>${badge(x.status)}</div><p>${esc(x.pack_id||'未绑定设备')} · GPS ${x.gps_last_received_at_utc?`最近 ${fmtTime(x.gps_last_received_at_utc)}`:'暂无回传'}</p></div>`).join(''):'<div class="muted">暂无运行中被试</div>';$('attentionList').innerHTML=d.incidents.length?d.incidents.map(x=>`<div class="issue"><div class="issue-title"><strong>${esc(x.participant_id||'—')} · ${esc(x.summary||x.incident_type)}</strong>${badge(x.status)}</div><p>${esc(x.source)} · ${esc(x.date_local)}</p></div>`).join(''):'<div class="muted">暂无开放异常</div>'}
async function renderCandidates(){const a=await api('/api/v1/web/candidates');$('candidateRows').innerHTML=a.map(x=>`<tr><td>${esc(x.name||'—')}</td><td>${esc(x.phone)}<br><span class="muted">${esc(x.wechat)}</span></td><td>${esc(x.source)}</td><td>${esc([x.sex,x.age_group,x.identity_type].filter(Boolean).join(' · '))}</td><td>${esc([x.work_district,x.home_district].filter(Boolean).join(' / '))}</td><td>${esc(x.phone_os)}</td><td>${esc(x.linked_participant_id||'—')}</td><td>${x.linked_participant_id?'已入组':`<button class="btn small" data-promote="${esc(x.candidate_uid)}">赋ID/预约</button>`}</td></tr>`).join('');document.querySelectorAll('[data-promote]').forEach(b=>b.addEventListener('click',()=>openPromote(b.dataset.promote)))}
async function addCandidate(){const body={name:$('cName').value,phone:$('cPhone').value,wechat:$('cWechat').value,source:$('cSource').value,sex:$('cSex').value,age_group:$('cAge').value,identity_type:$('cIdentity').value,phone_os:$('cOs').value,work_district:$('cWork').value,home_district:$('cHome').value,availability:$('cAvail').value,notes:$('cNotes').value};await api('/api/v1/web/candidates',{method:'POST',body:JSON.stringify(body)});toast('已加入候选池');await renderCandidates()}
function openPromote(uid){selectedCandidate=uid;const t=new Date().toISOString().slice(0,10);$('pStart').value=t;const e=new Date();e.setDate(e.getDate()+13);$('pEnd').value=e.toISOString().slice(0,10);$('promoteDialog').showModal()}
async function promote(){const body={participant_id:$('pId').value,batch_id:$('pBatch').value,expected_start:$('pStart').value,expected_end:$('pEnd').value,pack_id:$('pPack').value,assigned_ra:$('pRa').value};await api(`/api/v1/web/candidates/${selectedCandidate}/promote`,{method:'POST',body:JSON.stringify(body)});$('promoteDialog').close();toast('已创建预约');await renderCandidates()}
async function renderSubjects(){const a=await api('/api/v1/web/subjects');$('subjectRows').innerHTML=a.map(x=>`<tr><td><strong>${esc(x.participant_id)}</strong></td><td>${esc(x.name||'—')}<br><span class="muted">${esc(x.phone||'')}</span></td><td>${badge(x.status)}</td><td>${esc(x.start_date||x.expected_start||'—')} → ${esc(x.end_date||x.expected_end||'—')}</td><td>${esc(x.pack_id||'—')}</td><td>${esc(x.assigned_ra||'—')}</td><td>${x.gps_last_received_at_utc?fmtTime(x.gps_last_received_at_utc):'暂无'}</td><td><div class="row">${x.status==='scheduled'?`<button class="btn small" data-start="${x.participant_id}" data-pack="${esc(x.pack_id)}">启动</button>`:''}<button class="btn small" data-gps="${x.participant_id}">GPS凭据</button></div></td></tr>`).join('');document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>openStart(b.dataset.start,b.dataset.pack)));document.querySelectorAll('[data-gps]').forEach(b=>b.addEventListener('click',()=>createGps(b.dataset.gps)))}
async function createGps(pid){if(!confirm(`为 ${pid} 创建一次性 GPS 密码？密码只显示这一次。`))return;try{const x=await api(`/api/v1/web/subjects/${pid}/gps-credential`,{method:'POST',body:'{}'});alert(`OwnTracks Username: ${pid}\nPassword: ${x.password}\n\n请立即保存，服务器只存 hash。`)}catch(e){alert(e.message)}}
function openStart(pid,pack){selectedSubject=pid;$('sPack').value=pack||'';const t=new Date().toISOString().slice(0,10);$('sStart').value=t;const e=new Date();e.setDate(e.getDate()+13);$('sEnd').value=e.toISOString().slice(0,10);$('startDialog').showModal()}
async function startSubject(){await api(`/api/v1/web/subjects/${selectedSubject}/start`,{method:'POST',body:JSON.stringify({pack_id:$('sPack').value,start_date:$('sStart').value,end_date:$('sEnd').value})});$('startDialog').close();toast('已启动运行');await renderSubjects()}
async function renderDevices(){const a=await api('/api/v1/web/devices');$('deviceRows').innerHTML=a.map(x=>`<tr><td><strong>${esc(x.pack_id)}</strong></td><td>${badge(x.status)}</td><td>${esc(x.current_participant_id||'—')}</td><td>${esc(x.light_serial||'—')}</td><td>${esc(x.ax3_serial||'—')}</td><td>${esc(x.issued_date||'—')}</td><td>${esc(x.expected_return_date||'—')}</td><td>${esc(x.notes||'')}</td></tr>`).join('')}
async function saveDevice(){await api('/api/v1/web/devices',{method:'POST',body:JSON.stringify({pack_id:$('dPack').value,status:$('dStatus').value,light_serial:$('dLight').value,ax3_serial:$('dAx3').value,notes:$('dNotes').value})});toast('设备包已保存');await renderDevices()}
async function renderIncidents(){const a=await api('/api/v1/web/incidents');$('incidentList').innerHTML=a.length?a.map(x=>`<div class="issue"><div class="issue-title"><div><strong>${esc(x.participant_id||'—')} · ${esc(x.summary||x.incident_type)}</strong> ${badge(x.status)}</div><span class="muted">${esc(x.date_local)}</span></div><p>${esc(x.source)} · ${esc(x.notes||'')}</p><div class="row" style="margin-top:7px">${x.status==='open'?`<button class="btn small" data-istatus="${x.incident_uid}" data-v="handling">标记处理中</button>`:''}${x.status!=='closed'?`<button class="btn small" data-istatus="${x.incident_uid}" data-v="closed">关闭</button>`:''}</div></div>`).join(''):'<div class="muted">暂无异常</div>';document.querySelectorAll('[data-istatus]').forEach(b=>b.addEventListener('click',()=>setIncidentStatus(b.dataset.istatus,b.dataset.v)))}
async function addIncident(){await api('/api/v1/web/incidents',{method:'POST',body:JSON.stringify({participant_id:$('iPid').value,date_local:$('iDate').value,source:$('iSource').value,incident_type:$('iType').value,severity:$('iSeverity').value,summary:$('iSummary').value,notes:$('iNotes').value})});toast('已加入异常中心');await renderIncidents()}
async function setIncidentStatus(uid,v){await api(`/api/v1/web/incidents/${uid}/status`,{method:'POST',body:JSON.stringify({status:v})});await renderIncidents()}
async function renderSources(){const a=await api('/api/v1/web/data-sources');$('sourceGrid').innerHTML=a.map(x=>`<div class="source"><div class="row" style="justify-content:space-between"><div class="name">${esc(x.name)}</div>${badge(x.status)}</div><dl><dt>进入方式</dt><dd>${esc(x.acquisition)}</dd><dt>存储</dt><dd>${esc(x.storage)}</dd><dt>自动化</dt><dd>${esc(x.automation)}</dd>${x.records!==null?`<dt>当前记录</dt><dd>${x.records}</dd>`:''}${x.last_event?`<dt>最近事件</dt><dd>${fmtTime(x.last_event)}</dd>`:''}</dl></div>`).join('')}
async function renderArchitecture(){const x=await api('/api/v1/web/architecture');$('architectureView').innerHTML=`<div class="arch"><div class="arch-row"><div class="node"><div class="k">People</div><strong>PI / RA</strong><span class="muted">浏览器维护实验运营</span></div><div class="node"><div class="k">Participant</div><strong>Participants</strong><span class="muted">OwnTracks / 上传 / 问卷</span></div><div class="node"><div class="k">Interface</div><strong>LEHUE Web Admin</strong><span class="muted">同一可视化管理入口</span></div><div class="node"><div class="k">Backend</div><strong>FastAPI</strong><span class="muted">身份、状态、API、规则</span></div></div><div class="arrow">↓</div><div class="arch-row"><div class="node"><div class="k">Realtime source</div><strong>GPS / OwnTracks</strong><span class="muted">已接入</span></div><div class="node"><div class="k">Large file source</div><strong>Lighting / OSS</strong><span class="muted">接口预留</span></div><div class="node"><div class="k">Manual source</div><strong>问卷星</strong><span class="muted">人工下载 → 自动导入（预留）</span></div><div class="node"><div class="k">Offline source</div><strong>AX3</strong><span class="muted">回收后导入（预留）</span></div></div><div class="arrow">↓</div><div class="arch-row"><div class="node"><div class="k">Sensitive</div><strong>Identity DB</strong><span class="muted">姓名、电话、管理员账号</span></div><div class="node"><div class="k">Pseudonymous</div><strong>Operations + GPS DB</strong><span class="muted">被试ID、设备、异常、GPS</span></div><div class="node"><div class="k">Future raw vault</div><strong>OSS</strong><span class="muted">大体量原始文件</span></div><div class="node"><div class="k">Scientific analysis</div><strong>Local workstation</strong><span class="muted">科研QC与统计分析不搬云端</span></div></div><div class="card" style="box-shadow:none;margin:8px 0 0;background:var(--soft2)"><strong>边界：</strong> ${esc(x.principle)}</div></div>`}
async function renderUsers(){const a=await api('/api/v1/web/users');$('userRows').innerHTML=a.map(x=>{const self=x.username===me.username;return `<tr><td><strong>${esc(x.username)}</strong>${self?' <span class="muted">（当前）</span>':''}</td><td>${esc(x.display_name||'—')}</td><td>${badge(x.role)}</td><td>${badge(x.is_active?'active':'inactive')}</td><td>${fmtTime(x.created_at_utc)}</td><td><div class="user-actions"><button class="btn small" data-reset="${esc(x.username)}">重置密码</button>${self?'':`<button class="btn small ${x.is_active?'danger':''}" data-active="${esc(x.username)}" data-v="${x.is_active?'0':'1'}">${x.is_active?'禁用':'启用'}</button>`}</div></td></tr>`}).join('');document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',()=>resetUserPassword(b.dataset.reset)));document.querySelectorAll('[data-active]').forEach(b=>b.addEventListener('click',()=>setUserActive(b.dataset.active,b.dataset.v==='1')))}
async function addUser(){try{const x=await api('/api/v1/web/users',{method:'POST',body:JSON.stringify({username:$('uUsername').value,display_name:$('uDisplay').value,role:$('uRole').value,password:$('uPassword').value})});alert(`账号已创建\n\nUsername: ${x.username}\nPassword: ${x.password}\n\n请立即交给对应协作者。服务器只存密码 hash。`);$('uPassword').value='';await renderUsers()}catch(e){alert(e.message)}}
async function resetUserPassword(username){if(!confirm(`重置 ${username} 的密码？现有登录会失效。`))return;try{const x=await api(`/api/v1/web/users/${encodeURIComponent(username)}/reset-password`,{method:'POST',body:'{}'});alert(`新密码（只显示这一次）\n\n${x.password}`);if(username===me.username)location.reload();else await renderUsers()}catch(e){alert(e.message)}}
async function setUserActive(username,isActive){try{await api(`/api/v1/web/users/${encodeURIComponent(username)}/active`,{method:'POST',body:JSON.stringify({is_active:isActive})});toast(isActive?'账号已启用':'账号已禁用');await renderUsers()}catch(e){alert(e.message)}}
async function downloadBackup(){const b=$('backupBtn');b.disabled=true;b.textContent='正在生成…';try{const r=await fetch('/api/v1/web/backup');if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.detail||`HTTP ${r.status}`)}const blob=await r.blob();const cd=r.headers.get('content-disposition')||'';const m=cd.match(/filename="?([^";]+)"?/i);const name=m?m[1]:'LEHUE_system_backup.zip';const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast('备份已生成并下载')}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='下载系统状态备份'}}

$('setupBtn').addEventListener('click',firstSetup);$('setupPassword2').addEventListener('keydown',e=>{if(e.key==='Enter')firstSetup()});$('loginBtn').addEventListener('click',login);$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',()=>loadTab(activeTab));$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)showTab(b.dataset.tab)});$('addCandidateBtn').addEventListener('click',addCandidate);$('promoteSubmit').addEventListener('click',promote);$('startSubmit').addEventListener('click',startSubject);$('saveDeviceBtn').addEventListener('click',saveDevice);$('addIncidentBtn').addEventListener('click',addIncident);$('addUserBtn').addEventListener('click',addUser);$('backupBtn').addEventListener('click',downloadBackup);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
initialize();
